version: '3'

services:
  sinsungo:
    image: wisdomsg/sinsungo:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"


